### ISSUE TITLE
Multiple-day event not showing event times on event tile and event details page.

### ISSUE THREAD

**Issue by dasithds** [marcom-unimelb/matrix-controlled-environment#177]
Hi guys,

So there is a small problem with multiple-day events: Both the event tile and event details page do not display the time of the event. Can you please look into this? 

Here is an example: http://arts.unimelb.edu.au/news/details?event=6995

Thanks!!
Dasith.

**Comment by tomstringer** [comment]
Hey Dasith

This is a tricky one. The events.unimelb API provides only a single start and end datetime for events. 

In this case, the start/end date/timestamp for this event looks like this: 

```"start_time": "2016-07-28T18:15:00+10:00" - "end_time": "2016-11-10T20:30:00+11:00"```

That could mean that on every one of those days, the event starts at 6:15pm and ends at 8:30pm.

OR

It could be something like an exhibition that has its opening on the first day at 6:15pm and closes on its last day at 8:30pm, but every day in between, it may be open 9am to 5pm.

There's no way in the API (as it is currently constructed) to identify which of these it might be.

The template is designed to pick up whether or not an event is a multiday event, and because of this ambiguity, just show general information (like the start and end dates). We need to rely on booking links, details within the event itself, or "more information" URLs to provide that added detail.

My recommendation would be to make sure that people submitting mutliday events (that will be consumed by your feed) are instructed to added separate start/end times where relevant.

**Comment by dasithds** [comment]
Hey Tom,

I didn't realize that you had replied to the ticket until I saw this now.
Earlier during the semester I switched to my staff account for user access
to the CMS but I didn't realize that my github login was still associated
to my student email. I'll change that right away.

Thanks for the reply by the way. I'll speak to the stakeholders and explain
this.

Best regards,
Dasith.
