### ISSUE TITLE
Local Event label not updated by "keyword" metadata field

### ISSUE THREAD

**Issue by jporich** [marcom-unimelb/matrix-controlled-environment#202]
Event label is not being updated when filling in the "keyword" field in metadata (see screen shot)

Intended effect is listed in web resources: https://resources.web.unimelb.edu.au/controlled-environment/news/keywords-now-in-use
<img width="1426" alt="events label static" src="https://cloud.githubusercontent.com/assets/10070570/19787604/4afe5a24-9cef-11e6-80c0-deaa59ab9e5c.png">

**Comment by yevek** [comment]
example page: http://mspgh.unimelb.edu.au/news-and-events/research-with-and-for-children-half-day-seminar

**Comment by tomstringer** [comment]
That's been done intentionally for local assets because I'm not sure everyone uses the tag_keyword field the same way. 

The bottom-right corner of the block event assets is intended to show the type of event. Event labels from events.unimelb have a specific set of event type values that can be selected so can be used consistently, but for local Matrix assets, the tag_keyword is an open text field. 

So people may use that field for identifying a speaker, or some other piece of information.

@yevek What are your thoughts?

**Comment by yevek** [comment]
@tomstringer I think it would be good to include it so that we are consistent. I had a quick look and it should be possible to include a conditional statement.

**Comment by yevek** [comment]
Hey Jimmy I have added the tagging for events. You can see an example of this here: http://biomedicalsciences.unimelb.edu.au/news-and-events/_recache 

Closing this off.

**Comment by jporich** [comment]
¸.•*¨*•♫♪¸¸.•*¨*•♫♪¸¸.•*¨*•♫♪uhhhh maazziiinnggggg!¸¸.•*¨*•♫♪¸¸.•*¨*•♫♪¸¸.•*¨*•♫♪¸¸.•*¨*•♫♪

Cheers Donna ☺


Jimmy Porich  |  Web Content and Development Coordinator
External Relations  |  University Services

Level 2, 32 North Lincoln Square
The University of Melbourne, Victoria 3010 Australia
T: (03) 9035 8072 E: james.porich@unimelb.edu.au<mailto:james.porich@unimelb.edu.au>


[cid:image001.png@01D2514D.122741E0]


This email and any attachments may contain personal information or  information that is otherwise confidential or the subject of copyright. Any use, disclosure or copying of any part of it is prohibited. The University does not warrant that this email or any attachments are free from viruses or defects. Please check any attachments for viruses and defects before opening them. If this email is received in error please delete it and notify us by return email.
