### ISSUE TITLE
Filtered Listing Page showing unstyled checkbox after latest MCE style update

### ISSUE THREAD

**Issue by jporich** [marcom-unimelb/matrix-controlled-environment#203]
Example page:
<img width="1397" alt="visible unstyled checkboxes" src="https://cloud.githubusercontent.com/assets/10070570/19794048/44376b5a-9d1b-11e6-8af5-f6306bd623a2.png">
http://psychologicalsciences.unimelb.edu.au/study/current-students/student-forms

Seems to be caused by line 148 in uom-mce.css:
/* 21/10/16 unstyled form overrides for checkboxes to work */
.uomcontent#top form:not(.unstyled-controls) fieldset input[type=checkbox]:not(.unstyled),
.uomcontent#top form:not(.unstyled-controls) fieldset input[type=radio]:not(.unstyled) {
  position: static !important;
}

Notes: 
1. Can't find another example page sorry! :( most of our pages using filtered listings are in bespoke
2. The example in Web Components appears to be working fine, but it doesn't seem to have uom-mce.css applied, only uom.css http://web.unimelb.edu.au/components/filtered-listings/

**Comment by yevek** [comment]
checking with Design Team about this one.

**Comment by yevek** [comment]
@jporich have put in css fix for that issue thanks for reporting. 

I see you've hard-coded in all code for this page. You'll need also need to update those manually as per v5.0 breaking changes here: https://resources.web.unimelb.edu.au/controlled-environment/news/mce-v5.0/aside-changes I'd also suggest using the "blank template" instead of the inside page no header so that you can add your own custom header in - it looks a bit funny in the blue template.

![image](https://cloud.githubusercontent.com/assets/1305804/19795275/fc5ab534-9d25-11e6-81a8-f239660465d8.png)

**Comment by jporich** [comment]
Cheers,

This page wasn’t me! Just distancing myself from the odd design choice, haha – but agreed, I’ll go through and give it a makeover.

Also: superfast! – thank you ☺


Jimmy Porich  |  Web Content and Development Coordinator
External Relations  |  University Services

Level 2, 32 North Lincoln Square
The University of Melbourne, Victoria 3010 Australia
T: (03) 9035 8072 E: james.porich@unimelb.edu.au<mailto:james.porich@unimelb.edu.au>


[cid:image001.png@01D23133.B2279F80]


This email and any attachments may contain personal information or  information that is otherwise confidential or the subject of copyright. Any use, disclosure or copying of any part of it is prohibited. The University does not warrant that this email or any attachments are free from viruses or defects. Please check any attachments for viruses and defects before opening them. If this email is received in error please delete it and notify us by return email.
