### ISSUE TITLE
date/time css override on forms

### ISSUE THREAD

**Issue by yevek** [marcom-unimelb/matrix-controlled-environment#97]
Do date/time example for forms, to fix this issue. 

https://cms.unimelb.edu.au/controlled-environment/guide/using-forms/default-form/_nocache

![date-time-overirdes](https://cloud.githubusercontent.com/assets/1305804/15131820/a30bdf96-1696-11e6-9b69-938eff1da912.png)

**Comment by patpaev** [comment]
For anyone interested in a quick fix, you can make it look like this:

<img width="677" alt="screen shot 2016-05-19 at 4 07 47 pm" src="https://cloud.githubusercontent.com/assets/6847023/15384185/dd1b6836-1ddb-11e6-8fa6-175600bd67a7.png">

By pasting the following snippet into a component field (I used 'Alert text'), as it looks like Squiz doesn't have any sanitisation rules when it comes to that.

```
<style>
  .sq-form-question-datetime label {   
    width: 20%!important;   box-sizing: border-box;   float: left; 
  }  

  .sq-form-question-datetime fieldset .styled-select {   
    width: 19%!important;
    display: inline-block!important;
    margin-right: 1%!important;
    float: right!important; 
  } 
</style>
```

**Comment by yevek** [comment]
thanks @patpaev  we will do some testing and see if we can't get that into our CSS file. 

Did you have to add custom HTML to the page contents, or is the CSS override enough?

**Comment by patpaev** [comment]
All just CSS, @yevek ! :smile:

**Comment by FPG-Github** [comment]
Nice, very nice...

This works because the Alert field component is basically a metadata field used by a text block that to render text on the page and is not used to drive the templates, hence it injects the style code straight into the text block on  the page untouched. Problem is that adding the CSS into the Alert field also makes the form render a blank Alert Box as per the screen grab. So for this hack would also need to add some CSS to hide the <p class="alert-info"> off screen.

Equivalent in the MCE would be to use the Introductory text metadata field under the Content tab - but again it then adds a blank <section class="lead"> that adds a bunch of white space into the top of the page.

We're looking at the best way to drop the styling into the system in the back end, either as part of the Design System CSS or within the templates (would need to be done specifically for the MCE and Staff Hub).

**Comment by FPG-Github** [comment]
Nice, very nice...

This works because the Alert field component is basically a metadata field used by a text block that to render text on the page and is not used to drive the templates, hence it injects the style code straight into the text block on  the page untouched. Problem is that adding the CSS into the Alert field also makes the form render a blank Alert Box as per the screen grab. So for this hack would also need to add some CSS to hide the <p class="alert-info"> off screen.

Equivalent in the MCE would be to use the Introductory text metadata field under the Content tab - but again it then adds a blank <section class="lead"> that adds a bunch of white space into the top of the page.

We're looking at the best way to drop the styling into the system in the back end, either as part of the Design System CSS or within the templates (would need to be done specifically for the MCE and Staff Hub).
